In [1]:
EsFeatures = {}

In [2]:
EsFeatures['a'] = set(('low', 'front', 'lax', 'unrounded')) 
EsFeatures['e'] = set(('mid', 'front', 'tense', 'unrounded')) 
EsFeatures['i'] = set(('high', 'front', 'tense', 'unrounded')) 
EsFeatures['o'] = set(('mid', 'back', 'tense', 'rounded')) 
EsFeatures['u'] = set(('high', 'back', 'tense', 'rounded')) 
EsFeatures['ɛ'] = set(('mid', 'front', 'lax', 'unrounded')) 
EsFeatures['ɪ'] = set(('high', 'front', 'lax', 'unrounded')) 
EsFeatures['n'] = set(('nasal', 'alveolar', 'voiced'))
EsFeatures['f'] = set(('fricative', 'labiodental', 'voiceless'))
EsFeatures['m'] = set(('nasal', 'bilabial', 'voiced'))
EsFeatures['b'] = set(('plosive', 'bilabial', 'voiced'))
EsFeatures['ɾ'] = set(('tap', 'alveolar','voiced'))
EsFeatures['k'] = set(('plosive', 'velar', 'voiceless'))
EsFeatures['l'] = set(('lateral approximant', 'alveolar', 'voiced'))
EsFeatures['d'] = set(('plosive','alveolar','voiced'))
EsFeatures['v'] = set(('fricative', 'labiodental','voiceless'))
EsFeatures['p'] = set(('plosive', 'bilabial','voiceless'))
EsFeatures['j'] = set(('approximant', 'palatal','voiced'))
EsFeatures['ð'] = set(('fricative', 'dental','voiced'))
EsFeatures['w'] = set(('approximant','bilabial','voiced'))
EsFeatures['ʃ'] = set(('fricative', 'post-alveolar','voiceless'))
EsFeatures['t'] = set(('plosive', 'alveolar', 'voiceless'))
EsFeatures['ɡ'] = set(('plosive', 'velar', 'voiced'))
EsFeatures['ŋ'] = set(('nasal', 'velar','voiced'))
EsFeatures['s'] = set(('fricative','alveolar', 'voiceless'))
EsFeatures['d͡ʒ'] = set(('affricate', 'post-alveolar', 'voiced'))
EsFeatures['t͡ʃ'] = set(('affricate', 'post-alveolar', 'voiceless'))
EsFeatures['β'] = set(('fricative' 'bilabial', 'voiced'))
EsFeatures['x'] = set(('fricative', 'velar', 'voiceless'))
EsFeatures['ɣ'] = set(('fricative', 'velar', 'voiced'))
EsFeatures['ʝ'] = set(('fricative', 'palatal', 'voiced'))
EsFeatures['ʎ'] = set(('lateral approximant', 'palatal', 'voiced'))


In [3]:
esvowels = set(('a', 'e', 'i', 'o', 'u', 'ɛ', 'ɪ'))

In [4]:
escons = set(('n', 'f', 'm', 'b', 'ɾ', 'k','l', 'd', 'v', 'p', 'j', 'ð', 'w', 'ʃ', 't', 'ɡ', 'ŋ', 's', 'd͡ʒ', 't͡ʃ', 'β', 'x', 'ɣ', 'ʝ', 'ʎ'))

In [73]:
import numpy

def matrix(token1, token2): 
    
    distances = numpy.zeros((len(token1) + 1, len(token2) + 1)) 
    
    for t1 in range(len(token1) + 1):
        distances[t1][0] = t1
    for t2 in range(len(token2) + 1):
        distances[0][t2] = t2   
    
    a = 0
    b = 0
    c = 0
    
    return distances
    

def penalty(t1, t2, distances, penalty): 
    
    a = distances[t1][t2 - 1]
    b = distances[t1 - 1][t2]
    c = distances[t1 - 1][t2 - 1]
    
    if (a <= b and a <= c):
        distances[t1][t2] = a + penalty
    elif (b <= a and b <= c):
        distances[t1][t2] = b + penalty
    else:
        distances[t1][t2] = c + penalty
    
    return distances 

def OldLD(token1, token2): 
    
    distances = matrix(token1, token2)

    for t1 in range(1, len(token1) + 1):
        for t2 in range(1, len(token2) + 1):   
            if (token1[t1-1] == token2[t2-1]):
                distances[t1][t2] = distances[t1-1][t2-1]
            else:
                if token1[t1-1] in escons: 
                    if token2[t2-1] in escons:
                        if len(EsFeatures[token1[t1-1]]-EsFeatures[token2[t2-1]]) == 1: 
                            distances = penalty(t1, t2, distances, .3)
                        elif len(EsFeatures[token1[t1-1]]-EsFeatures[token2[t2-1]]) == 2:
                            distances = penalty(t1, t2, distances, .6)
                        else: 
                            distances = penalty(t1, t2, distances, 1)
                    else:
                        distances = penalty(t1, t2, distances, 1) 
                elif token1[t1-1] in esvowels: 
                    if token2[t2-1] in esvowels: 
                        if len(EsFeatures[token1[t1-1]]-EsFeatures[token2[t2-1]]) == 1: 
                            distances = penalty(t1, t2, distances, .25)
                        elif len(EsFeatures[token1[t1-1]]-EsFeatures[token2[t2-1]]) == 2:
                            distances = penalty(t1, t2, distances, .5)
                        elif len(EsFeatures[token1[t1-1]]-EsFeatures[token2[t2-1]]) == 3:
                            distances = penalty(t1, t2, distances, .75)
                        else: 
                            distances = penalty(t1, t2, distances, 1) 
                    else: 
                        distances = penalty(t1, t2, distances, 1) 
                else:
                    distances = penalty(t1, t2, distances, 1)  
                    
    return distances, distances[len(token1)][len(token2)]

         
    
  
    

In [70]:
OldLD('deðo', 'peɾðon')

(array([[0. , 1. , 2. , 3. , 4. , 5. , 6. ],
        [1. , 0.6, 1.6, 1.9, 2.5, 3.5, 3.8],
        [2. , 1.6, 0.6, 1.6, 2.6, 3. , 4. ],
        [3. , 2.6, 1.6, 1.2, 1.6, 2.6, 3.2],
        [4. , 3.6, 2.1, 2.2, 2.2, 1.6, 2.6]]),
 2.6)

In [71]:
OldLD('pip', 'bipp')

(array([[0. , 1. , 2. , 3. , 4. ],
        [1. , 0.3, 1.3, 2. , 3. ],
        [2. , 1.3, 0.3, 1.3, 2.3],
        [3. , 1.6, 1.3, 0.3, 1.3]]),
 1.3)

In [78]:
OldLD('abc', 'xyzc')

(array([[0., 1., 2., 3., 4.],
        [1., 1., 2., 3., 4.],
        [2., 2., 2., 3., 4.],
        [3., 3., 3., 3., 3.]]),
 3.0)

In [77]:
OldLD('ab ', 'xyz ')

(array([[0., 1., 2., 3., 4.],
        [1., 1., 2., 3., 4.],
        [2., 2., 2., 3., 4.],
        [3., 3., 3., 3., 3.]]),
 3.0)

In [79]:
OldLD('abxc', 'xyzc')

(array([[0., 1., 2., 3., 4.],
        [1., 1., 2., 3., 4.],
        [2., 2., 2., 3., 4.],
        [3., 2., 3., 3., 4.],
        [4., 3., 3., 4., 3.]]),
 3.0)