In [4]:
EsFeatures = {}

In [5]:
EsFeatures['a'] = set(('low', 'front', 'lax', 'unrounded')) 
EsFeatures['e'] = set(('mid', 'front', 'tense', 'unrounded')) 
EsFeatures['i'] = set(('high', 'front', 'tense', 'unrounded')) 
EsFeatures['o'] = set(('mid', 'back', 'tense', 'rounded')) 
EsFeatures['u'] = set(('high', 'back', 'tense', 'rounded')) 
EsFeatures['ɛ'] = set(('mid', 'front', 'lax', 'unrounded')) 
EsFeatures['ɪ'] = set(('high', 'front', 'lax', 'unrounded')) 
EsFeatures['n'] = set(('nasal', 'alveolar', 'voiced'))
EsFeatures['f'] = set(('fricative', 'labiodental', 'voiceless'))
EsFeatures['m'] = set(('nasal', 'bilabial', 'voiced'))
EsFeatures['b'] = set(('plosive', 'bilabial', 'voiced'))
EsFeatures['ɾ'] = set(('tap', 'alveolar','voiced'))
EsFeatures['k'] = set(('plosive', 'velar', 'voiceless'))
EsFeatures['l'] = set(('lateral approximant', 'alveolar', 'voiced'))
EsFeatures['d'] = set(('plosive','alveolar','voiced'))
EsFeatures['v'] = set(('fricative', 'labiodental','voiceless'))
EsFeatures['p'] = set(('plosive', 'bilabial','voiceless'))
EsFeatures['j'] = set(('approximant', 'palatal','voiced'))
EsFeatures['ð'] = set(('fricative', 'dental','voiced'))
EsFeatures['w'] = set(('approximant','bilabial','voiced'))
EsFeatures['ʃ'] = set(('fricative', 'post-alveolar','voiceless'))
EsFeatures['t'] = set(('plosive', 'alveolar', 'voiceless'))
EsFeatures['ɡ'] = set(('plosive', 'velar', 'voiced'))
EsFeatures['ŋ'] = set(('nasal', 'velar','voiced'))
EsFeatures['s'] = set(('fricative','alveolar', 'voiceless'))
EsFeatures['d͡ʒ'] = set(('affricate', 'post-alveolar', 'voiced'))
EsFeatures['t͡ʃ'] = set(('affricate', 'post-alveolar', 'voiceless'))
EsFeatures['β'] = set(('fricative' 'bilabial', 'voiced'))
EsFeatures['x'] = set(('fricative', 'velar', 'voiceless'))
EsFeatures['ɣ'] = set(('fricative', 'velar', 'voiced'))
EsFeatures['ʝ'] = set(('fricative', 'palatal', 'voiced'))
EsFeatures['ʎ'] = set(('lateral approximant', 'palatal', 'voiced'))


In [6]:
esvowels = set(('a', 'e', 'i', 'o', 'u', 'ɛ', 'ɪ'))

In [7]:
escons = set(('n', 'f', 'm', 'b', 'ɾ', 'k','l', 'd', 'v', 'p', 'j', 'ð', 'w', 'ʃ', 't', 'ɡ', 'ŋ', 's', 'd͡ʒ', 't͡ʃ', 'β', 'x', 'ɣ', 'ʝ', 'ʎ'))

In [8]:
import numpy


def PhonemePrep(token1, token2): 

    if len(token1) < len(token2): 
        for char in range(len(token1), len(token2)):
            token1 = token1 + " "
            token2 = token2
    elif len(token1) > len(token2): 
        for char in range(len(token2), len(token1)): 
            token2 = token2 + " "
            
    return token1, token2

def LD(token1, token2): 
    
    pp = PhonemePrep(token1, token2)
    token1 = pp[0]
    token2 = pp[1]
    
    distances = numpy.zeros((len(token1) + 1, len(token2) + 1)) 
    for t1 in range(len(token1) + 1):
        distances[t1][0] = t1
    for t2 in range(len(token2) + 1):
        distances[0][t2] = t2   
    
    
    score = 0
    i = 1
    for t1, t2 in zip(token1, token2): 
        if t1 == t2:
            distances[i][i] = score
            i += 1
            continue
        else: 
            if t1 in escons: 
                if t2 in escons: 
                    if len(EsFeatures[t1]-EsFeatures[t2]) == 1: 
                        score += .3
                        distances[i][i] = score
                    elif len(EsFeatures[t1]-EsFeatures[t2]) == 2:
                        score += .6
                        distances[i][i] = score
                    else: 
                        score += 1
                        distances[i][i] = score
                else: 
                    score += 1
                    distances[i][i] = score
            elif t1 in esvowels: 
                if t2 in esvowels: 
                    if len(EsFeatures[t1]-EsFeatures[t2]) == 1: 
                        score += .25
                        distances[i][i] = score
                    elif len(EsFeatures[t1]-EsFeatures[t2]) == 2:
                        score += .5
                        distances[i][i] = score
                    elif len(EsFeatures[t1]-EsFeatures[t2]) == 2:
                        score += .75
                        distances[i][i] = score
                    else: 
                        score += 1
                        distances[i][i] = score
                else: 
                    score += 1
                    distances[i][i] = score
            else:
                score += 1
                distances[i][i] = score
            i += 1
            
    return score, distances



    

In [14]:
LD('pip', 'pip')

(0,
 array([[0., 1., 2., 3.],
        [1., 0., 0., 0.],
        [2., 0., 0., 0.],
        [3., 0., 0., 0.]]))

In [15]:
LD('bip', 'pip')

(0.3,
 array([[0. , 1. , 2. , 3. ],
        [1. , 0.3, 0. , 0. ],
        [2. , 0. , 0.3, 0. ],
        [3. , 0. , 0. , 0.3]]))

In [9]:
LD('pebb','bib ')


(1.55,
 array([[0.  , 1.  , 2.  , 3.  , 4.  ],
        [1.  , 0.3 , 0.  , 0.  , 0.  ],
        [2.  , 0.  , 0.55, 0.  , 0.  ],
        [3.  , 0.  , 0.  , 0.55, 0.  ],
        [4.  , 0.  , 0.  , 0.  , 1.55]]))

In [10]:
LD('bib', 'pebb')

(1.55,
 array([[0.  , 1.  , 2.  , 3.  , 4.  ],
        [1.  , 0.3 , 0.  , 0.  , 0.  ],
        [2.  , 0.  , 0.55, 0.  , 0.  ],
        [3.  , 0.  , 0.  , 0.55, 0.  ],
        [4.  , 0.  , 0.  , 0.  , 1.55]]))

In [11]:
LD('bib', 'bib bib')

(3,
 array([[0., 1., 2., 3., 4., 5., 6., 7.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0.],
        [4., 0., 0., 0., 0., 0., 0., 0.],
        [5., 0., 0., 0., 0., 1., 0., 0.],
        [6., 0., 0., 0., 0., 0., 2., 0.],
        [7., 0., 0., 0., 0., 0., 0., 3.]]))

In [13]:
LD('bib bib', 'bib')

(3,
 array([[0., 1., 2., 3., 4., 5., 6., 7.],
        [1., 0., 0., 0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0., 0., 0.],
        [4., 0., 0., 0., 0., 0., 0., 0.],
        [5., 0., 0., 0., 0., 1., 0., 0.],
        [6., 0., 0., 0., 0., 0., 2., 0.],
        [7., 0., 0., 0., 0., 0., 0., 3.]]))